### ISSUE TITLE
how to access `swagger-ui.html`

### ISSUE THREAD

**Issue by Anricx** [grpc-swagger/grpc-swagger#15]
how to access `swagger-ui.html` like `http://ui.grpcs.top/#/` does?
I only have `grpc-swagger-web` and a running grpc services.

**Comment by zhangjikai** [comment]
直接使用 http://ui.grpcs.top/#/ 这个就行，在输入框里填入 http://<your-host:ip>/v2/api-docs?service=<service-name>

**Comment by airoasis** [comment]
http://your-host:port/v2/api-docs?service=service-name shows the api documents in text not UI
