### ISSUE TITLE
after deployed，Access URL :http://localhost:8080 can't display swagger ui

### ISSUE THREAD

**Issue by abirdman** [grpc-swagger/grpc-swagger#19]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Sep 04 22:30:59 CST 2019
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by zhangjikai** [comment]
这个里面没有swagger-ui，swagger-ui 可以用这个 http://ui.grpcs.top/

**Comment by abirdman** [comment]
http://ui.grpcs.top/访问非常慢，http://ui.grpcs.top/也是grpc-swagger项目配套的吗？还是有某个开源项目能拿来我自己的服务器部署？如果有的话，麻烦也发个下载地址，谢谢！

**Comment by zhangjikai** [comment]
https://github.com/swagger-api/swagger-ui  用的这个，http://ui.grpcs.top/ 是在上面的基础上改了一下，功能都一样

**Comment by abirdman** [comment]
> https://github.com/swagger-api/swagger-ui 用的这个，http://ui.grpcs.top/ 是在上面的基础上改了一下，功能都一样

**Comment by abirdman** [comment]
好的，谢谢！
