### ISSUE TITLE
type of "bytes"  in proto file will not support

### ISSUE THREAD

**Issue by mbb1234567890** [grpc-swagger/grpc-swagger#24]
if message contends "bytes" , how can I send data?

```
message HelloRequest {
    string name = 1;
    bytes data = 2;
}
```

**Comment by liuzhengyang** [comment]
You can use base64 format. see [Protocol Buffers
 Guide](https://developers.google.com/protocol-buffers/docs/proto3?hl=zh-CN#json)
>JSON value will be the data encoded as a string using standard base64 encoding with paddings. Either standard or URL-safe base64 encoding with/without paddings are accepted.
