### ISSUE TITLE
header support

### ISSUE THREAD

**Issue by marchtea** [grpc-swagger/grpc-swagger#33]
How to add header when calling grpc?
UseCase:
> we are using jwt as head parameter(grpc md) to identify user info. So it's required to pass jwt token into md when debuging grpc. 
How to do this in grpc-swagger?

**Comment by zhangjikai** [comment]
Hi, we add a parameter named `headers`  and you can pass headers use this parameter. For this feature you need use the latest grpc-swagger [release](https://github.com/grpc-swagger/grpc-swagger/releases/tag/v0.1.7).  Detail change see #35 .

**Comment by marchtea** [comment]
it works great.
but there is duplicated service after register.
![image](https://user-images.githubusercontent.com/3918849/86320566-bc012100-bc69-11ea-87e7-01bc27c166df.png)
and this is grpcurl returns.
![image](https://user-images.githubusercontent.com/3918849/86320582-c4f1f280-bc69-11ea-8669-fba6a88fae03.png)

**Comment by zhangjikai** [comment]
fix in [new release](https://github.com/grpc-swagger/grpc-swagger/releases/tag/v0.1.8)
