### ISSUE TITLE
【bug】1.61.1 不能生成 HelloServiceGrpc，需要改为 1.31.1

### ISSUE THREAD

**Issue by TommyLemon** [grpc-swagger/grpc-swagger#37]
感谢这个项目。

https://github.com/grpc-swagger/grpc-swagger/blob/master/grpc-swagger-demo/pom.xml
中
```xml
                    <pluginArtifact>
                        io.grpc:protoc-gen-grpc-java:1.16.1:exe:${os.detected.classifier}
                    </pluginArtifact>
```
1.16.1 不能生成 HelloServiceGrpc.java，改成 1.13.1 再先后点击 
Plugins/protobuf/protobuf:compile
Plugins/protobuf/protobuf:compile-custom 
才能生成
![image](https://user-images.githubusercontent.com/5738175/91192353-69535b00-e728-11ea-84ea-ab717926deda.png)

![image](https://user-images.githubusercontent.com/5738175/91192246-4b85f600-e728-11ea-882b-3298f057ae34.png)

![image](https://user-images.githubusercontent.com/5738175/91192197-3e690700-e728-11ea-8aa2-b51b585da8cf.png)

**Comment by TommyLemon** [comment]
已发 PR
https://github.com/grpc-swagger/grpc-swagger/pull/38

**Comment by zhangjikai** [comment]
是不是环境配置的有问题，我这边可以的
