### ISSUE TITLE
How to enable grpc reflection if confuguring server using annontation 

### ISSUE THREAD

**Issue by dupinderdhiman** [grpc-swagger/grpc-swagger#45]
My question is very simple 

My GRPC server is configured in Sprinboot application using Annontation to the controller.

```
@GRpcService
public class DocumentServiceController extends DocumentServiceImplBase {
....
...
...
}
```

**Comment by zhangjikai** [comment]
https://github.com/LogNet/grpc-spring-boot-starter/pull/83

**Comment by dupinderdhiman** [comment]
So it was a simple solution

Open `application.properties` and add following line 
`grpc.enableReflection=true`
